name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: gcc -o hello.elf main.c
    - run: ./hello.elf
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "hello.elf"
        bodyFile: "body.md"
